baseurl = "https://serene-bartik-0bb54f.netlify.com"
title = "Blog"
author = "Olle Dahlen"
canonifyurls = true
languagecode = "en"
theme = "black-and-light"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Blog"
  disableWebFonts = false